name: Daily Alchemer to Zoho Sync

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5 AM UTC
  workflow_dispatch:      # Optional: allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          ALCHEMER_API_KEY: ${{ secrets.ALCHEMER_API_KEY }}
          ALCHEMER_API_SECRET: ${{ secrets.ALCHEMER_API_SECRET }}
          ALCHEMER_SURVEY_ID: ${{ secrets.ALCHEMER_SURVEY_ID }}
          ZOHO_AUTH_TOKEN: ${{ secrets.ZOHO_AUTH_TOKEN }}
          ZOHO_IMPORT_URL: ${{ secrets.ZOHO_IMPORT_URL }}
        run: python alchemer_to_zoho.py
